import type { InputUnit } from "@/lib/inventory/units";

export type IngredientCategory =
  | "meat"
  | "dairy"
  | "vegFruit"
  | "grain"
  | "spice";

export type IngredientCatalogItem = {
  id: string;
  nameTr: string;
  nameEn: string;
  emoji: string;
  category: IngredientCategory;
  defaultUnit: InputUnit;
};

export const CATEGORY_ORDER: IngredientCategory[] = [
  "spice",
  "meat",
  "vegFruit",
  "grain",
  "dairy",
];

export const INGREDIENT_CATALOG: IngredientCatalogItem[] = [
  // ---- ET VE ŞARKÜTERİ ----
  { id: "tavuk-gogsu", nameTr: "Tavuk Göğsü", nameEn: "Chicken Breast", emoji: "🍗", category: "meat", defaultUnit: "gr" },
  { id: "tavuk-but", nameTr: "Tavuk But", nameEn: "Chicken Thigh", emoji: "🍗", category: "meat", defaultUnit: "gr" },
  { id: "tavuk-kanat", nameTr: "Tavuk Kanat", nameEn: "Chicken Wing", emoji: "🍗", category: "meat", defaultUnit: "gr" },
  { id: "dana-kiyma", nameTr: "Dana Kıyma", nameEn: "Beef Mince", emoji: "🥩", category: "meat", defaultUnit: "gr" },
  { id: "kuzu-kiyma", nameTr: "Kuzu Kıyma", nameEn: "Lamb Mince", emoji: "🥩", category: "meat", defaultUnit: "gr" },
  { id: "dana-eti", nameTr: "Dana Eti", nameEn: "Beef", emoji: "🥩", category: "meat", defaultUnit: "gr" },
  { id: "kuzu-eti", nameTr: "Kuzu Eti", nameEn: "Lamb", emoji: "🥩", category: "meat", defaultUnit: "gr" },
  { id: "hindi", nameTr: "Hindi", nameEn: "Turkey", emoji: "🦃", category: "meat", defaultUnit: "gr" },
  { id: "sucuk", nameTr: "Sucuk", nameEn: "Sucuk", emoji: "🌭", category: "meat", defaultUnit: "gr" },
  { id: "sosis", nameTr: "Sosis", nameEn: "Sausage", emoji: "🌭", category: "meat", defaultUnit: "gr" },
  { id: "salam", nameTr: "Salam", nameEn: "Salami", emoji: "🥓", category: "meat", defaultUnit: "gr" },
  { id: "pastirma", nameTr: "Pastırma", nameEn: "Pastırma", emoji: "🥓", category: "meat", defaultUnit: "gr" },
  { id: "balik", nameTr: "Balık", nameEn: "Fish", emoji: "🐟", category: "meat", defaultUnit: "gr" },
  { id: "somon", nameTr: "Somon", nameEn: "Salmon", emoji: "🐟", category: "meat", defaultUnit: "gr" },
  { id: "levrek", nameTr: "Levrek", nameEn: "Sea Bass", emoji: "🐟", category: "meat", defaultUnit: "gr" },
  { id: "hamsi", nameTr: "Hamsi", nameEn: "Anchovy", emoji: "🐟", category: "meat", defaultUnit: "gr" },
  { id: "karides", nameTr: "Karides", nameEn: "Shrimp", emoji: "🦐", category: "meat", defaultUnit: "gr" },
  { id: "yumurta", nameTr: "Yumurta", nameEn: "Egg", emoji: "🥚", category: "meat", defaultUnit: "adet" },

  // ---- SÜT ÜRÜNLERİ ----
  { id: "sut", nameTr: "Süt", nameEn: "Milk", emoji: "🥛", category: "dairy", defaultUnit: "ml" },
  { id: "yogurt", nameTr: "Yoğurt", nameEn: "Yogurt", emoji: "🥣", category: "dairy", defaultUnit: "gr" },
  { id: "ayran", nameTr: "Ayran", nameEn: "Ayran", emoji: "🥤", category: "dairy", defaultUnit: "ml" },
  { id: "krema", nameTr: "Krema", nameEn: "Cream", emoji: "🥛", category: "dairy", defaultUnit: "ml" },
  { id: "kaymak", nameTr: "Kaymak", nameEn: "Clotted Cream", emoji: "🥣", category: "dairy", defaultUnit: "gr" },
  { id: "labne", nameTr: "Labne", nameEn: "Labneh", emoji: "🥣", category: "dairy", defaultUnit: "gr" },
  { id: "beyaz-peynir", nameTr: "Beyaz Peynir", nameEn: "Feta Cheese", emoji: "🧀", category: "dairy", defaultUnit: "gr" },
  { id: "kasar-peyniri", nameTr: "Kaşar Peyniri", nameEn: "Kaşar Cheese", emoji: "🧀", category: "dairy", defaultUnit: "gr" },
  { id: "lor-peyniri", nameTr: "Lor Peyniri", nameEn: "Lor Cheese", emoji: "🧀", category: "dairy", defaultUnit: "gr" },
  { id: "tulum-peyniri", nameTr: "Tulum Peyniri", nameEn: "Tulum Cheese", emoji: "🧀", category: "dairy", defaultUnit: "gr" },
  { id: "tereyagi", nameTr: "Tereyağı", nameEn: "Butter", emoji: "🧈", category: "dairy", defaultUnit: "gr" },
  { id: "margarin", nameTr: "Margarin", nameEn: "Margarine", emoji: "🧈", category: "dairy", defaultUnit: "gr" },

  // ---- SEBZE ----
  { id: "domates", nameTr: "Domates", nameEn: "Tomato", emoji: "🍅", category: "vegFruit", defaultUnit: "gr" },
  { id: "yesil-biber", nameTr: "Yeşil Biber", nameEn: "Green Pepper", emoji: "🌶️", category: "vegFruit", defaultUnit: "gr" },
  { id: "sivri-biber", nameTr: "Sivri Biber", nameEn: "Long Pepper", emoji: "🌶️", category: "vegFruit", defaultUnit: "gr" },
  { id: "dolmalik-biber", nameTr: "Dolmalık Biber", nameEn: "Bell Pepper", emoji: "🫑", category: "vegFruit", defaultUnit: "gr" },
  { id: "kapya-biber", nameTr: "Kapya Biber", nameEn: "Capia Pepper", emoji: "🌶️", category: "vegFruit", defaultUnit: "gr" },
  { id: "patlican", nameTr: "Patlıcan", nameEn: "Eggplant", emoji: "🍆", category: "vegFruit", defaultUnit: "gr" },
  { id: "kabak", nameTr: "Kabak", nameEn: "Zucchini", emoji: "🥒", category: "vegFruit", defaultUnit: "gr" },
  { id: "havuc", nameTr: "Havuç", nameEn: "Carrot", emoji: "🥕", category: "vegFruit", defaultUnit: "gr" },
  { id: "patates", nameTr: "Patates", nameEn: "Potato", emoji: "🥔", category: "vegFruit", defaultUnit: "gr" },
  { id: "tatli-patates", nameTr: "Tatlı Patates", nameEn: "Sweet Potato", emoji: "🍠", category: "vegFruit", defaultUnit: "gr" },
  { id: "sogan", nameTr: "Soğan", nameEn: "Onion", emoji: "🧅", category: "vegFruit", defaultUnit: "gr" },
  { id: "kuru-sogan", nameTr: "Kuru Soğan", nameEn: "Yellow Onion", emoji: "🧅", category: "vegFruit", defaultUnit: "gr" },
  { id: "sarimsak", nameTr: "Sarımsak", nameEn: "Garlic", emoji: "🧄", category: "vegFruit", defaultUnit: "gr" },
  { id: "marul", nameTr: "Marul", nameEn: "Lettuce", emoji: "🥬", category: "vegFruit", defaultUnit: "gr" },
  { id: "ispanak", nameTr: "Ispanak", nameEn: "Spinach", emoji: "🥬", category: "vegFruit", defaultUnit: "gr" },
  { id: "pirasa", nameTr: "Pırasa", nameEn: "Leek", emoji: "🥬", category: "vegFruit", defaultUnit: "gr" },
  { id: "brokoli", nameTr: "Brokoli", nameEn: "Broccoli", emoji: "🥦", category: "vegFruit", defaultUnit: "gr" },
  { id: "karnabahar", nameTr: "Karnabahar", nameEn: "Cauliflower", emoji: "🥦", category: "vegFruit", defaultUnit: "gr" },
  { id: "lahana", nameTr: "Lahana", nameEn: "Cabbage", emoji: "🥬", category: "vegFruit", defaultUnit: "gr" },
  { id: "kereviz", nameTr: "Kereviz", nameEn: "Celery", emoji: "🥬", category: "vegFruit", defaultUnit: "gr" },
  { id: "turp", nameTr: "Turp", nameEn: "Radish", emoji: "🥬", category: "vegFruit", defaultUnit: "gr" },
  { id: "pancar", nameTr: "Pancar", nameEn: "Beetroot", emoji: "🥬", category: "vegFruit", defaultUnit: "gr" },
  { id: "bamya", nameTr: "Bamya", nameEn: "Okra", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "enginar", nameTr: "Enginar", nameEn: "Artichoke", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "semizotu", nameTr: "Semizotu", nameEn: "Purslane", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "dereotu", nameTr: "Dereotu", nameEn: "Dill", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "maydanoz", nameTr: "Maydanoz", nameEn: "Parsley", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "taze-nane", nameTr: "Taze Nane", nameEn: "Fresh Mint", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "feslegen", nameTr: "Fesleğen", nameEn: "Basil", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "roka", nameTr: "Roka", nameEn: "Arugula", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "salatalik", nameTr: "Salatalık", nameEn: "Cucumber", emoji: "🥒", category: "vegFruit", defaultUnit: "gr" },
  { id: "taze-fasulye", nameTr: "Taze Fasulye", nameEn: "Green Beans", emoji: "🫛", category: "vegFruit", defaultUnit: "gr" },
  { id: "kuskonmaz", nameTr: "Kuşkonmaz", nameEn: "Asparagus", emoji: "🌿", category: "vegFruit", defaultUnit: "gr" },
  { id: "mantar", nameTr: "Mantar", nameEn: "Mushroom", emoji: "🍄", category: "vegFruit", defaultUnit: "gr" },
  { id: "misir", nameTr: "Mısır", nameEn: "Corn", emoji: "🌽", category: "vegFruit", defaultUnit: "gr" },

  // ---- MEYVE ----
  { id: "elma", nameTr: "Elma", nameEn: "Apple", emoji: "🍎", category: "vegFruit", defaultUnit: "gr" },
  { id: "yesil-elma", nameTr: "Yeşil Elma", nameEn: "Green Apple", emoji: "🍏", category: "vegFruit", defaultUnit: "gr" },
  { id: "portakal", nameTr: "Portakal", nameEn: "Orange", emoji: "🍊", category: "vegFruit", defaultUnit: "gr" },
  { id: "mandalina", nameTr: "Mandalina", nameEn: "Mandarin", emoji: "🍊", category: "vegFruit", defaultUnit: "gr" },
  { id: "limon", nameTr: "Limon", nameEn: "Lemon", emoji: "🍋", category: "vegFruit", defaultUnit: "gr" },
  { id: "muz", nameTr: "Muz", nameEn: "Banana", emoji: "🍌", category: "vegFruit", defaultUnit: "gr" },
  { id: "cilek", nameTr: "Çilek", nameEn: "Strawberry", emoji: "🍓", category: "vegFruit", defaultUnit: "gr" },
  { id: "ahududu", nameTr: "Ahududu", nameEn: "Raspberry", emoji: "🫐", category: "vegFruit", defaultUnit: "gr" },
  { id: "yaban-mersini", nameTr: "Yaban Mersini", nameEn: "Blueberry", emoji: "🫐", category: "vegFruit", defaultUnit: "gr" },
  { id: "uzum", nameTr: "Üzüm", nameEn: "Grape", emoji: "🍇", category: "vegFruit", defaultUnit: "gr" },
  { id: "nar", nameTr: "Nar", nameEn: "Pomegranate", emoji: "🍎", category: "vegFruit", defaultUnit: "gr" },
  { id: "karpuz", nameTr: "Karpuz", nameEn: "Watermelon", emoji: "🍉", category: "vegFruit", defaultUnit: "gr" },
  { id: "kavun", nameTr: "Kavun", nameEn: "Melon", emoji: "🍈", category: "vegFruit", defaultUnit: "gr" },
  { id: "kayisi", nameTr: "Kayısı", nameEn: "Apricot", emoji: "🍑", category: "vegFruit", defaultUnit: "gr" },
  { id: "seftali", nameTr: "Şeftali", nameEn: "Peach", emoji: "🍑", category: "vegFruit", defaultUnit: "gr" },
  { id: "kiraz", nameTr: "Kiraz", nameEn: "Cherry", emoji: "🍒", category: "vegFruit", defaultUnit: "gr" },
  { id: "visne", nameTr: "Vişne", nameEn: "Sour Cherry", emoji: "🍒", category: "vegFruit", defaultUnit: "gr" },
  { id: "erik", nameTr: "Erik", nameEn: "Plum", emoji: "🍑", category: "vegFruit", defaultUnit: "gr" },
  { id: "incir", nameTr: "İncir", nameEn: "Fig", emoji: "🍑", category: "vegFruit", defaultUnit: "gr" },
  { id: "avokado", nameTr: "Avokado", nameEn: "Avocado", emoji: "🥑", category: "vegFruit", defaultUnit: "adet" },
  { id: "ananas", nameTr: "Ananas", nameEn: "Pineapple", emoji: "🍍", category: "vegFruit", defaultUnit: "gr" },
  { id: "mango", nameTr: "Mango", nameEn: "Mango", emoji: "🥭", category: "vegFruit", defaultUnit: "gr" },
  { id: "kivi", nameTr: "Kivi", nameEn: "Kiwi", emoji: "🥝", category: "vegFruit", defaultUnit: "adet" },

  // ---- BAKLİYAT / TAHIL / KURU GIDA ----
  { id: "pirinc", nameTr: "Pirinç", nameEn: "Rice", emoji: "🍚", category: "grain", defaultUnit: "gr" },
  { id: "basmati-pirinc", nameTr: "Basmati Pirinç", nameEn: "Basmati Rice", emoji: "🍚", category: "grain", defaultUnit: "gr" },
  { id: "bulgur", nameTr: "Bulgur", nameEn: "Bulgur", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "kepek-bulgur", nameTr: "Köftelik Bulgur", nameEn: "Fine Bulgur", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "makarna", nameTr: "Makarna", nameEn: "Pasta", emoji: "🍝", category: "grain", defaultUnit: "gr" },
  { id: "spagetti", nameTr: "Spagetti", nameEn: "Spaghetti", emoji: "🍝", category: "grain", defaultUnit: "gr" },
  { id: "sehriye", nameTr: "Şehriye", nameEn: "Orzo", emoji: "🍝", category: "grain", defaultUnit: "gr" },
  { id: "eriste", nameTr: "Erişte", nameEn: "Erişte", emoji: "🍜", category: "grain", defaultUnit: "gr" },
  { id: "kuskus", nameTr: "Kuskus", nameEn: "Couscous", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "yulaf", nameTr: "Yulaf", nameEn: "Oats", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "kinoa", nameTr: "Kinoa", nameEn: "Quinoa", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "un", nameTr: "Un", nameEn: "Flour", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "tam-bugday-unu", nameTr: "Tam Buğday Unu", nameEn: "Whole Wheat Flour", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "misir-unu", nameTr: "Mısır Unu", nameEn: "Cornmeal", emoji: "🌽", category: "grain", defaultUnit: "gr" },
  { id: "nisasta", nameTr: "Nişasta", nameEn: "Starch", emoji: "🌾", category: "grain", defaultUnit: "gr" },
  { id: "ekmek", nameTr: "Ekmek", nameEn: "Bread", emoji: "🍞", category: "grain", defaultUnit: "gr" },
  { id: "pide", nameTr: "Pide", nameEn: "Pita", emoji: "🍞", category: "grain", defaultUnit: "adet" },
  { id: "lavas", nameTr: "Lavaş", nameEn: "Lavash", emoji: "🫓", category: "grain", defaultUnit: "adet" },
  { id: "yufka", nameTr: "Yufka", nameEn: "Phyllo", emoji: "🫓", category: "grain", defaultUnit: "adet" },
  { id: "galeta-unu", nameTr: "Galeta Unu", nameEn: "Breadcrumbs", emoji: "🍞", category: "grain", defaultUnit: "gr" },
  { id: "kirmizi-mercimek", nameTr: "Kırmızı Mercimek", nameEn: "Red Lentil", emoji: "🫘", category: "grain", defaultUnit: "gr" },
  { id: "yesil-mercimek", nameTr: "Yeşil Mercimek", nameEn: "Green Lentil", emoji: "🫘", category: "grain", defaultUnit: "gr" },
  { id: "nohut", nameTr: "Nohut", nameEn: "Chickpea", emoji: "🫘", category: "grain", defaultUnit: "gr" },
  { id: "kuru-fasulye", nameTr: "Kuru Fasulye", nameEn: "White Beans", emoji: "🫘", category: "grain", defaultUnit: "gr" },
  { id: "barbunya", nameTr: "Barbunya", nameEn: "Borlotti Beans", emoji: "🫘", category: "grain", defaultUnit: "gr" },
  { id: "siyah-fasulye", nameTr: "Siyah Fasulye", nameEn: "Black Beans", emoji: "🫘", category: "grain", defaultUnit: "gr" },
  { id: "bezelye", nameTr: "Bezelye", nameEn: "Peas", emoji: "🫛", category: "grain", defaultUnit: "gr" },
  { id: "ceviz", nameTr: "Ceviz", nameEn: "Walnut", emoji: "🌰", category: "grain", defaultUnit: "gr" },
  { id: "findik", nameTr: "Fındık", nameEn: "Hazelnut", emoji: "🌰", category: "grain", defaultUnit: "gr" },
  { id: "fistik", nameTr: "Fıstık", nameEn: "Pistachio", emoji: "🥜", category: "grain", defaultUnit: "gr" },
  { id: "badem", nameTr: "Badem", nameEn: "Almond", emoji: "🥜", category: "grain", defaultUnit: "gr" },
  { id: "kaju", nameTr: "Kaju", nameEn: "Cashew", emoji: "🥜", category: "grain", defaultUnit: "gr" },
  { id: "cam-fistigi", nameTr: "Çam Fıstığı", nameEn: "Pine Nut", emoji: "🥜", category: "grain", defaultUnit: "gr" },
  { id: "yer-fistigi", nameTr: "Yer Fıstığı", nameEn: "Peanut", emoji: "🥜", category: "grain", defaultUnit: "gr" },
  { id: "kuru-uzum", nameTr: "Kuru Üzüm", nameEn: "Raisins", emoji: "🍇", category: "grain", defaultUnit: "gr" },
  { id: "kuru-kayisi", nameTr: "Kuru Kayısı", nameEn: "Dried Apricot", emoji: "🍑", category: "grain", defaultUnit: "gr" },
  { id: "hurma", nameTr: "Hurma", nameEn: "Date", emoji: "🌴", category: "grain", defaultUnit: "gr" },
  { id: "maya", nameTr: "Maya", nameEn: "Yeast", emoji: "🥣", category: "grain", defaultUnit: "gr" },
  { id: "kabartma-tozu", nameTr: "Kabartma Tozu", nameEn: "Baking Powder", emoji: "🥣", category: "grain", defaultUnit: "gr" },
  { id: "karbonat", nameTr: "Karbonat", nameEn: "Baking Soda", emoji: "🥣", category: "grain", defaultUnit: "gr" },

  // ---- BAHARAT VE SOSLAR ----
  { id: "tuz", nameTr: "Tuz", nameEn: "Salt", emoji: "🧂", category: "spice", defaultUnit: "gr" },
  { id: "karabiber", nameTr: "Karabiber", nameEn: "Black Pepper", emoji: "⚫", category: "spice", defaultUnit: "gr" },
  { id: "pul-biber", nameTr: "Pul Biber", nameEn: "Chili Flakes", emoji: "🌶️", category: "spice", defaultUnit: "gr" },
  { id: "toz-biber", nameTr: "Kırmızı Toz Biber", nameEn: "Paprika", emoji: "🌶️", category: "spice", defaultUnit: "gr" },
  { id: "kimyon", nameTr: "Kimyon", nameEn: "Cumin", emoji: "🌿", category: "spice", defaultUnit: "gr" },
  { id: "kekik", nameTr: "Kekik", nameEn: "Thyme", emoji: "🌿", category: "spice", defaultUnit: "gr" },
  { id: "kuru-nane", nameTr: "Kuru Nane", nameEn: "Dried Mint", emoji: "🌿", category: "spice", defaultUnit: "gr" },
  { id: "tarcin", nameTr: "Tarçın", nameEn: "Cinnamon", emoji: "🟤", category: "spice", defaultUnit: "gr" },
  { id: "zerdecal", nameTr: "Zerdeçal", nameEn: "Turmeric", emoji: "🟡", category: "spice", defaultUnit: "gr" },
  { id: "zencefil", nameTr: "Zencefil", nameEn: "Ginger", emoji: "🫚", category: "spice", defaultUnit: "gr" },
  { id: "sumak", nameTr: "Sumak", nameEn: "Sumac", emoji: "🟣", category: "spice", defaultUnit: "gr" },
  { id: "defne", nameTr: "Defne Yaprağı", nameEn: "Bay Leaf", emoji: "🌿", category: "spice", defaultUnit: "gr" },
  { id: "safran", nameTr: "Safran", nameEn: "Saffron", emoji: "🟡", category: "spice", defaultUnit: "gr" },
  { id: "vanilya", nameTr: "Vanilya", nameEn: "Vanilla", emoji: "🌼", category: "spice", defaultUnit: "gr" },
  { id: "karanfil", nameTr: "Karanfil", nameEn: "Cloves", emoji: "🌿", category: "spice", defaultUnit: "gr" },
  { id: "muskat", nameTr: "Muskat", nameEn: "Nutmeg", emoji: "🌰", category: "spice", defaultUnit: "gr" },
  { id: "domates-salcasi", nameTr: "Domates Salçası", nameEn: "Tomato Paste", emoji: "🥫", category: "spice", defaultUnit: "gr" },
  { id: "biber-salcasi", nameTr: "Biber Salçası", nameEn: "Pepper Paste", emoji: "🥫", category: "spice", defaultUnit: "gr" },
  { id: "ketcap", nameTr: "Ketçap", nameEn: "Ketchup", emoji: "🥫", category: "spice", defaultUnit: "ml" },
  { id: "mayonez", nameTr: "Mayonez", nameEn: "Mayonnaise", emoji: "🥫", category: "spice", defaultUnit: "gr" },
  { id: "hardal", nameTr: "Hardal", nameEn: "Mustard", emoji: "🥫", category: "spice", defaultUnit: "gr" },
  { id: "soya-sosu", nameTr: "Soya Sosu", nameEn: "Soy Sauce", emoji: "🍶", category: "spice", defaultUnit: "ml" },
  { id: "sirke", nameTr: "Sirke", nameEn: "Vinegar", emoji: "🍶", category: "spice", defaultUnit: "ml" },
  { id: "elma-sirkesi", nameTr: "Elma Sirkesi", nameEn: "Apple Vinegar", emoji: "🍶", category: "spice", defaultUnit: "ml" },
  { id: "nar-eksisi", nameTr: "Nar Ekşisi", nameEn: "Pomegranate Sauce", emoji: "🍶", category: "spice", defaultUnit: "ml" },
  { id: "limon-suyu", nameTr: "Limon Suyu", nameEn: "Lemon Juice", emoji: "🍋", category: "spice", defaultUnit: "ml" },
  { id: "zeytin", nameTr: "Zeytin", nameEn: "Olives", emoji: "🫒", category: "spice", defaultUnit: "gr" },
  { id: "zeytinyagi", nameTr: "Zeytinyağı", nameEn: "Olive Oil", emoji: "🫒", category: "spice", defaultUnit: "ml" },
  { id: "sivi-yag", nameTr: "Sıvı Yağ", nameEn: "Vegetable Oil", emoji: "🛢️", category: "spice", defaultUnit: "ml" },
  { id: "aycicek-yagi", nameTr: "Ayçiçek Yağı", nameEn: "Sunflower Oil", emoji: "🌻", category: "spice", defaultUnit: "ml" },
  { id: "susam-yagi", nameTr: "Susam Yağı", nameEn: "Sesame Oil", emoji: "🌾", category: "spice", defaultUnit: "ml" },
  { id: "seker", nameTr: "Şeker", nameEn: "Sugar", emoji: "🍬", category: "spice", defaultUnit: "gr" },
  { id: "esmer-seker", nameTr: "Esmer Şeker", nameEn: "Brown Sugar", emoji: "🍬", category: "spice", defaultUnit: "gr" },
  { id: "pudra-sekeri", nameTr: "Pudra Şekeri", nameEn: "Powdered Sugar", emoji: "🍬", category: "spice", defaultUnit: "gr" },
  { id: "bal", nameTr: "Bal", nameEn: "Honey", emoji: "🍯", category: "spice", defaultUnit: "gr" },
  { id: "pekmez", nameTr: "Pekmez", nameEn: "Molasses", emoji: "🍯", category: "spice", defaultUnit: "ml" },
  { id: "recel", nameTr: "Reçel", nameEn: "Jam", emoji: "🍯", category: "spice", defaultUnit: "gr" },
  { id: "tahin", nameTr: "Tahin", nameEn: "Tahini", emoji: "🥣", category: "spice", defaultUnit: "gr" },
  { id: "kakao", nameTr: "Kakao", nameEn: "Cocoa", emoji: "🍫", category: "spice", defaultUnit: "gr" },
  { id: "cikolata", nameTr: "Çikolata", nameEn: "Chocolate", emoji: "🍫", category: "spice", defaultUnit: "gr" },
  { id: "bitter-cikolata", nameTr: "Bitter Çikolata", nameEn: "Dark Chocolate", emoji: "🍫", category: "spice", defaultUnit: "gr" },
  { id: "susam", nameTr: "Susam", nameEn: "Sesame", emoji: "🌾", category: "spice", defaultUnit: "gr" },
  { id: "cay", nameTr: "Çay", nameEn: "Tea", emoji: "🍵", category: "spice", defaultUnit: "gr" },
  { id: "kahve", nameTr: "Kahve", nameEn: "Coffee", emoji: "☕", category: "spice", defaultUnit: "gr" },
  { id: "su", nameTr: "Su", nameEn: "Water", emoji: "💧", category: "spice", defaultUnit: "ml" },
  { id: "maden-suyu", nameTr: "Maden Suyu", nameEn: "Mineral Water", emoji: "💧", category: "spice", defaultUnit: "ml" },
];

export function getCatalogByCategory(
  category: IngredientCategory | "all",
): IngredientCatalogItem[] {
  if (category === "all") return INGREDIENT_CATALOG;
  return INGREDIENT_CATALOG.filter((item) => item.category === category);
}
