export const COMMON_INGREDIENTS: string[] = [
  "Tavuk", "Tavuk Göğsü", "Tavuk But", "Dana Kıyma", "Kuzu Kıyma", "Kuzu Eti",
  "Dana Eti", "Sığır Eti", "Hindi", "Sucuk", "Sosis", "Pastırma", "Balık", "Somon",
  "Karides", "Yumurta",
  "Süt", "Yoğurt", "Krema", "Kaymak", "Labne", "Beyaz Peynir", "Kaşar Peynir",
  "Lor Peyniri", "Tulum Peyniri", "Tereyağı", "Margarin",
  "Pirinç", "Bulgur", "Makarna", "Şehriye", "Tel Şehriye", "Erişte", "Un",
  "Mısır Unu", "Nişasta", "Ekmek", "Pide", "Lavaş", "Galeta Unu", "Yufka",
  "Mercimek", "Kırmızı Mercimek", "Yeşil Mercimek", "Nohut", "Fasulye",
  "Kuru Fasulye", "Barbunya",
  "Domates", "Biber", "Sivri Biber", "Dolmalık Biber", "Patlıcan", "Kabak",
  "Havuç", "Patates", "Soğan", "Sarımsak", "Marul", "Ispanak", "Pırasa",
  "Brokoli", "Karnabahar", "Lahana", "Kereviz", "Turp", "Pancar", "Bamya",
  "Enginar", "Bezelye", "Semizotu", "Dereotu", "Maydanoz", "Nane", "Fesleğen",
  "Roka", "Salatalık", "Taze Fasulye", "Kuşkonmaz", "Mantar",
  "Elma", "Portakal", "Limon", "Muz", "Çilek", "Üzüm", "Nar", "Karpuz", "Kavun",
  "Kayısı", "Şeftali", "Kiraz", "Vişne", "Erik", "İncir", "Avokado",
  "Zeytinyağı", "Sıvı Yağ", "Ayçiçek Yağı", "Tereyağı", "Susam Yağı",
  "Tuz", "Karabiber", "Pul Biber", "Kırmızı Toz Biber", "Kimyon", "Kekik",
  "Nane (Kuru)", "Tarçın", "Zerdeçal", "Zencefil", "Sumak", "Defne Yaprağı",
  "Safran", "Vanilya", "Karanfil", "Muskat",
  "Domates Salçası", "Biber Salçası", "Ketçap", "Mayonez", "Hardal",
  "Soya Sosu", "Sirke", "Nar Ekşisi", "Limon Suyu", "Zeytin",
  "Şeker", "Pudra Şekeri", "Bal", "Pekmez", "Reçel", "Tahin",
  "Kakao", "Çikolata", "Bitter Çikolata",
  "Maya", "Kabartma Tozu", "Vanilya Özü",
  "Ceviz", "Fındık", "Fıstık", "Badem", "Kaju", "Çam Fıstığı", "Susam",
  "Çay", "Kahve", "Su", "Sıcak Su", "Maden Suyu", "Ayran",
];
